name: Build Android & iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Test Android App
        run: ./gradlew test

      - name: Build Android App
        run: ./gradlew :androidApp:assembleDebug

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: androidApp-apk
          path: androidApp/build/outputs/apk/debug/*.apk
      
      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: testers
          file: androidApp/build/outputs/apk/debug/androidApp-debug.apk

  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: iosApp/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('iosApp/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build KMM iOS Framework
        run: ./gradlew :shared:podPublishXCFramework

      - name: Generate Dummy Framework for CocoaPods
        run: ./gradlew :shared:generateDummyFramework

      - name: Set up Ruby & CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install CocoaPods
        run: |
          cd iosApp
          pod install

      - name: Build iOS App (Archive)
        run: |
          cd iosApp
          xcodebuild -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -sdk iphonesimulator \
            -configuration Debug \
            -archivePath $PWD/build/iosApp.xcarchive \
            archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      
      # - name: Export IPA
      #   run: |
      #     cd iosApp
      #     xcodebuild -exportArchive \
      #       -archivePath build/iosApp.xcarchive \
      #       -exportPath build/ipa-out \
      #       -exportOptionsPlist ExportOptions.plist

      # - name: Upload IPA Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: iosApp-ipa
      #     path: iosApp/build/ipa-out/*.ipa

